"""
Turn every literal hex colour in the stylesheets into a CSS variable, then emit a
dark palette for those variables.

Value-based rather than role-based on purpose: this stylesheet already uses each hex
consistently for one job (#dfe3da is always a hairline border, #f3f4ef always the page
ground), so mapping per value preserves meaning without anyone hand-classifying 220
colours. Light mode is unchanged by construction — each var resolves to its original.
"""
import colorsys
import pathlib
import re

STYLES = pathlib.Path('src/renderer/src/styles')
FILES = ['globals.css', 'management.css', 'desktop.css']
HEX = re.compile(r'#([0-9a-fA-F]{3,8})\b')


def normalise(raw: str) -> tuple[str, str]:
    """Return (6-digit rgb, alpha suffix) for any 3/4/6/8-digit hex."""
    if len(raw) in (3, 4):
        rgb = ''.join(c * 2 for c in raw[:3])
        alpha = raw[3] * 2 if len(raw) == 4 else ''
    else:
        rgb = raw[:6]
        alpha = raw[6:8]
    return rgb.lower(), alpha.lower()


def darken(rgb: str, alpha: str = '') -> str:
    """Map a light-theme colour to its dark-theme counterpart."""
    # Translucent colours are shadows, scrims and tints layered over something else.
    # Flipping them turns drop shadows into halos and the modal backdrop into fog,
    # so they keep their value and simply sit on a darker ground.
    if alpha:
        return rgb

    r, g, b = (int(rgb[i:i + 2], 16) / 255 for i in (0, 2, 4))
    h, l, s = colorsys.rgb_to_hls(r, g, b)

    # Judge neutrality by chroma, not HSL saturation: saturation is unstable near
    # white and black, and reports #f3f4ef (a warm off-white ground) as 19% and
    # #13272a (near-black ink) as 38%, which would spare both from inversion.
    chroma = max(r, g, b) - min(r, g, b)

    if chroma < 0.10:
        # Near-neutral: flip lightness so grounds go dark and ink goes light,
        # keeping a trace of the original warmth rather than going flat grey.
        nl = min(max(1.0 - l, 0.10), 0.94)
        ns = min(s * 0.5, 0.08)
    else:
        # Accents keep their identity; nudge toward legibility on a dark ground.
        ns = s
        if l > 0.62:
            nl = l - 0.10
        elif l < 0.38:
            nl = l + 0.20
        else:
            nl = l + 0.04
        nl = min(max(nl, 0.22), 0.80)

    nr, ng, nb = colorsys.hls_to_rgb(h, nl, ns)
    return ''.join(f'{round(c * 255):02x}' for c in (nr, ng, nb))


# Colour keywords are invisible to the hex scanner, so a literal `white` survives
# tokenisation and then fails to invert — which is how calendar pills ended up with
# light backgrounds and light text in dark mode. Flag them instead of silently passing.
KEYWORDS = re.compile(
    r'(?<![-\w])(white|black|red|green|blue|grey|gray|silver|ivory|snow|beige|orange'
    r'|yellow|purple|pink|brown|navy|teal|olive|maroon|lime|aqua|fuchsia)(?![-\w])'
)


def warn_about_keywords() -> None:
    for name in FILES:
        for number, line in enumerate((STYLES / name).read_text().splitlines(), 1):
            if line.lstrip().startswith(('/*', '*')):
                continue
            for match in KEYWORDS.finditer(line):
                print(f'  WARNING {name}:{number} untokenised colour keyword {match.group(1)!r}')


def main() -> None:
    found: dict[str, None] = {}

    # Pass 1 — collect, ignoring anything already inside a var() fallback.
    for name in FILES:
        for match in HEX.finditer((STYLES / name).read_text()):
            rgb, alpha = normalise(match.group(1))
            found[rgb + alpha] = None

    # Pass 2 — rewrite literals to var() references.
    for name in FILES:
        path = STYLES / name
        text = path.read_text()

        def swap(match: re.Match[str]) -> str:
            rgb, alpha = normalise(match.group(1))
            return f'var(--c-{rgb}{alpha})'

        path.write_text(HEX.sub(swap, text))

    light, dark = [], []
    for key in sorted(found):
        rgb, alpha = key[:6], key[6:]
        light.append(f'  --c-{key}: #{rgb}{alpha};')
        dark.append(f'  --c-{key}: #{darken(rgb, alpha)}{alpha};')

    (STYLES / 'theme.css').write_text(
        '/* Generated by scripts/tokenize.py — do not hand-edit the blocks below.\n'
        '   Every literal colour in the other stylesheets resolves through these, so the\n'
        '   light values are exactly what the design shipped with. Overrides that need a\n'
        '   human eye live in theme-overrides.css, which loads after this file. */\n\n'
        ':root {\n' + '\n'.join(light) + '\n}\n\n'
        ':root[data-theme=\'dark\'] {\n' + '\n'.join(dark) + '\n}\n'
    )
    print(f'{len(found)} colours tokenised into theme.css')
    warn_about_keywords()


if __name__ == '__main__':
    main()
